import type { FC, SVGProps } from "react";
import {
  LangChainIcon,
  LlamaIndexIcon,
  VercelIcon,
  MCPServerIcon,
  ClaudeCodeIcon,
  OpenCodeIcon,
  CodexCliIcon,
  VSCodeIcon,
  CursorIcon,
  SmitheryIcon,
  AgentSkillsIcon,
  GoogleIcon,
  BingIcon,
  YahooIcon,
  LinkedInIcon,
  XIcon,
  GitHubIcon,
  NpmIcon,
  PypiIcon,
  PackagistIcon,
  Nodejs,
  PhpIcon,
} from "./brand";

export {
  LangChainIcon,
  LlamaIndexIcon,
  VercelIcon,
  MCPServerIcon,
  ClaudeCodeIcon,
  OpenCodeIcon,
  CodexCliIcon,
  VSCodeIcon,
  CursorIcon,
  SmitheryIcon,
  AgentSkillsIcon,
  GoogleIcon,
  BingIcon,
  YahooIcon,
  LinkedInIcon,
  XIcon,
  GitHubIcon,
  NpmIcon,
  PypiIcon,
  PackagistIcon,
  Nodejs,
  PhpIcon,
};

export const brandIcons: Record<string, FC<SVGProps<SVGSVGElement>>> = {
  Google: GoogleIcon,
  Bing: BingIcon,
  Yahoo: YahooIcon,
  GitHub: GitHubIcon,
  LinkedIn: LinkedInIcon,
  X: XIcon,
  Npm: NpmIcon,
  Pypi: PypiIcon,
  Packagist: PackagistIcon,
  LangChain: LangChainIcon,
  LlamaIndex: LlamaIndexIcon,
  Vercel: VercelIcon,
  MCPServer: MCPServerIcon,
  ClaudeCode: ClaudeCodeIcon,
  OpenCode: OpenCodeIcon,
  CodexCli: CodexCliIcon,
  VSCode: VSCodeIcon,
  Cursor: CursorIcon,
  Smithery: SmitheryIcon,
  AgentSkills: AgentSkillsIcon,
  Nodejs: Nodejs,
  Php: PhpIcon,
};
