export const googleShoppingResponse = {
  "status": "success",
  "msg": "Completed",
  "results": {
    "search_metadata": {
      "id": 245561757,
      "status": "success",
      "created_at": "2026-06-17T04:00:03.000000Z",
      "processed_at": "2026-06-17 04:00:03"
    },
    "search_parameters": {
      "domain": "google.com",
      "lang": "en",
      "country": "US",
      "location": "Abernathy,Texas,United States",
      "q": "iPhone",
      "device": "desktop",
      "url": "https://www.google.com/search?q=iPhone&uule=w+CAIQICIdQWJlcm5hdGh5LFRleGFzLFVuaXRlZCBTdGF0ZXM=&hl=en&gl=US&ie=UTF-8&udm=28",
      "page": "1",
      "num": 10,
      "ie": "UTF-8",
      "udm": "28"
    },
    "results": {
      "search_information": {
        "total_results": 50
      },
      "organic": [
        {
          "position": 1,
          "title": "Apple iPhone 16",
          "link": null,
          "product_link": null,
          "source": "Best Buy",
          "price": "$729.99",
          "rating": "4.6",
          "badge": "LOW PRICE ",
          "store_rating": "4.6",
          "store_review": "(24K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 2,
          "title": "Apple iPhone 16 Plus",
          "link": null,
          "product_link": null,
          "source": "Swappa",
          "price": "$627.00",
          "rating": "4.7",
          "badge": "30% OFF ",
          "store_rating": "4.7",
          "store_review": "(8.8K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": "Free delivery",
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 3,
          "title": "Apple iPhone 15",
          "link": null,
          "product_link": null,
          "source": "eBay",
          "price": "$3,000.00",
          "rating": "4.7",
          "badge": null,
          "store_rating": "4.7",
          "store_review": "(53K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 4,
          "title": "iPhone 15 256GB - Black - Unlocked",
          "link": null,
          "product_link": null,
          "source": "Back Market",
          "price": "$429.00",
          "rating": "4.7",
          "badge": "48% OFF ",
          "store_rating": "4.7",
          "store_review": "(53K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 5,
          "title": "Apple iPhone 16 Pro",
          "link": null,
          "product_link": null,
          "source": "eBay - sellingtech13",
          "price": "$669.99",
          "rating": "4.6",
          "badge": null,
          "store_rating": "4.6",
          "store_review": "(18K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": "Free delivery",
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 6,
          "title": "Apple iPhone 14",
          "link": null,
          "product_link": null,
          "source": "Walmart - Cell Surfers",
          "price": "$304.97",
          "rating": "4.6",
          "badge": null,
          "store_rating": "4.6",
          "store_review": "(49K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 7,
          "title": "Apple iPhone 14 Pro",
          "link": null,
          "product_link": null,
          "source": "Back Market",
          "price": "$464.64",
          "rating": "4.3",
          "badge": "53% OFF ",
          "store_rating": "4.3",
          "store_review": "(15K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 8,
          "title": "Apple iPhone 14 Pro Max",
          "link": null,
          "product_link": null,
          "source": "Back Market",
          "price": "$489.00",
          "rating": "4.4",
          "badge": "55% OFF ",
          "store_rating": "4.4",
          "store_review": "(23K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 9,
          "title": "Apple iPhone 7",
          "link": null,
          "product_link": null,
          "source": "eBay - sarahcell",
          "price": "$62.00",
          "rating": "4.3",
          "badge": null,
          "store_rating": "4.3",
          "store_review": "(49K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 10,
          "title": "Apple iPhone 14 Plus",
          "link": null,
          "product_link": null,
          "source": "Back Market",
          "price": "$402.00",
          "rating": "4.4",
          "badge": "60% OFF ",
          "store_rating": "4.4",
          "store_review": "(12K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 11,
          "title": "Straight Talk Apple iPhone 13, 128gb, Midnight - Prepaid Smartphone [Locked to Straight Talk], Size: 128 GB",
          "link": null,
          "product_link": null,
          "source": "Walmart",
          "price": "$199.00",
          "rating": "4.6",
          "badge": null,
          "store_rating": "4.6",
          "store_review": "(76K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": [
            " Nearby, 25 mi "
          ]
        },
        {
          "position": 12,
          "title": "Apple iPhone 17 Pro",
          "link": null,
          "product_link": null,
          "source": "Apple",
          "price": "$62.45/mo",
          "rating": "4.5",
          "badge": null,
          "store_rating": "4.5",
          "store_review": "(17K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 13,
          "title": "Apple iPhone 17 Pro Max",
          "link": null,
          "product_link": null,
          "source": "AT&amp;T",
          "price": "$33.34/mo",
          "rating": "4.4",
          "badge": null,
          "store_rating": "4.4",
          "store_review": "(24K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": [
            " Nearby, 21 mi "
          ]
        },
        {
          "position": 14,
          "title": "Apple iPhone 17",
          "link": null,
          "product_link": null,
          "source": "Apple",
          "price": "$829.00",
          "rating": "4.7",
          "badge": " 180 ",
          "store_rating": "4.7",
          "store_review": "(22K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        },
        {
          "position": 15,
          "title": "Apple iPhone 16e",
          "link": null,
          "product_link": null,
          "source": "Best Buy",
          "price": "$449.02",
          "rating": "4.6",
          "badge": "25% OFF ",
          "store_rating": "4.6",
          "store_review": "(11K)",
          "store_badge": null,
          "thumbnail": "src:BASE64",
          "delivery": null,
          "comparison_link": null,
          "extensions": null
        }
      ]
    }
  }
} as const;
