export const googleLocalResponse = {
  "status": "success",
  "msg": "Completed",
  "results": {
    "search_metadata": {
      "id": 236494291,
      "status": "success",
      "created_at": "2026-05-01T04:32:49.000000Z",
      "processed_at": "2026-05-01 04:32:49"
    },
    "search_parameters": {
      "domain": "google.com",
      "lang": "en",
      "country": "US",
      "location": "Austin,Texas,United States",
      "q": "Restaurants",
      "device": "desktop",
      "url": "https://www.google.com/search?q=Restaurants&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM=&hl=en&gl=US&ie=UTF-8&udm=1",
      "page": "1",
      "ie": "UTF-8",
      "udm": "1"
    },
    "results": {
      "search_information": [
        {
          "total_results": "241",
          "time_taken_displayed": "0.29"
        }
      ],
      "local_results": [
        {
          "position": 1,
          "title": "The Dead Rabbit, Austin",
          "rating": "4.4",
          "open_state": null,
          "reviews_count": "597",
          "top_review": "Great atmosphere, great service, great food & drink.",
          "place_id": "9065455841311406874",
          "description": null,
          "address": "204 E 6th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267721,
            "longitude": -97.74113
          },
          "type": "Restaurant",
          "price": "$20–30",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGV-m48VsiqHEPU9kAeQEFelGhLAlZ_gNjS1ifHPSNo7kgmFAzjP7urk0yd08LzonaPshZzCUEX1cV3GNKlI19i35YJFGVmXXPHRMekPQ-dxGF2IfN2DEQQqGZ7tcsS7ssRSHU=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11tmj15z89&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iJ8suAzrmAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBA2JhcpoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyNWplVmRyYkhWU1dGbDRZVEZuTldKWWFERmxWVnBFV0ROS1UxWnNSUkFC4AEA-gEECCsQNA&phdesc=a9TYRN28-JQ",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267721,-97.74113"
        },
        {
          "position": 2,
          "title": "Cedar Door Patio Bar &amp; Grill",
          "rating": "4.3",
          "open_state": null,
          "reviews_count": "1.7K",
          "top_review": "Cedar Door hosted our staff dinner and it was an amazing experience.",
          "place_id": "9326134692469608318",
          "description": null,
          "address": "201 Brazos St bldg A",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.264093,
            "longitude": -97.742584
          },
          "type": "Grill",
          "price": "$20–30",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGXktFb0OXI_G6S43WXFhmbgb1KJpRr3WD4SYC_ujFlGMb_8W73Ki7cdWtyPsN55u7aDBMF4YrL7avO4PekLL1-DI39u31Rpfd22UlJ4shoutIJkMiH0k1t_H3wIivpJgEjH25z=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/1tdqbzfj&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iw85XL5YCAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBDWJhcl9hbmRfZ3JpbGyaAURDaTlEUVVsUlFVTnZaRU5vZEhsalJqbHZUMnBPVEUxc1pFTlpibVJNVmtSb2FGTnRiRzlUYkdjd1l6Tm9UMkZGUlJBQuABAPoBBAgAEEQ&phdesc=Yoi5eGHcZSA",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.264093,-97.742584"
        },
        {
          "position": 3,
          "title": "Corner Restaurant",
          "rating": "4.8",
          "open_state": "Closes soon  · 12 AM",
          "reviews_count": "18K",
          "top_review": "The salmon salad, shrimp cocktail and short rib quesadillas were fire.",
          "place_id": "2814634074907806452",
          "description": null,
          "address": "110 E 2nd St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.26457,
            "longitude": -97.743835
          },
          "type": "Restaurant",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFwXEhp3kkHBSkf8zfVYHq8uf1E2WuqnmSbp_tfgKAhFPegXV78GIFO8ZSTl6zQn-dndOxZDZC_4UwQsIoLbfAtRkOrGwY7zyfW6CAv1hBJkHzlRa0B00EMCDNBdMuxaHIMner-gA=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11b76mjh5x&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0i8-eDpnKqAgAhaFxAAGAAiC3Jlc3RhdXJhbnRzKgQIAxAAkgEKcmVzdGF1cmFudJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOU01uSnRTVWRuRUFF4AEA-gEECAwQRg&phdesc=SHqhts431-I",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.26457,-97.743835"
        },
        {
          "position": 4,
          "title": "Happy Chicks",
          "rating": "4.1",
          "open_state": null,
          "reviews_count": "962",
          "top_review": "Wonderful food, hot, quick, perfectly executed.",
          "place_id": "5040330783418647592",
          "description": null,
          "address": "214 E 6th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267626,
            "longitude": -97.74078
          },
          "type": "Chicken",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFgzrXrFPvnUPwwFlDCcaovV0fwYwwW1RXBOVomJJfW5Xa80BecvSvJPhSmauS1-4HN-6BEwy0-5NWTI8HkhPX9GTiDt0nGG9ARgED0WZjBI__aKIjkCH0OQNMf1Lrc_gQyTgUq=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11f03yrvns&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iY1e--gK2AgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBEmNoaWNrZW5fcmVzdGF1cmFudJoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSNmQxQlhZbXBCUlJBQuABAPoBBQjiARAv&phdesc=kkIJyt3ygw4",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267626,-97.74078"
        },
        {
          "position": 5,
          "title": "Industry",
          "rating": "4.5",
          "open_state": null,
          "reviews_count": "1.4K",
          "top_review": "Drinks were delicious, food was delicious, and the service topped all of it.",
          "place_id": "4377382864982646783",
          "description": null,
          "address": "1211 E 5th St. Ste 150",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.262995,
            "longitude": -97.73012
          },
          "type": "Restaurant",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE997naI_qgIYlnLJC5AjvYjoz1SD9rgiqveXLrJDPzALhaYkm--kTsLdPOVNXDppxkq8lfwLvRQx8IKoja9eL1M6CWEZfitM4gKh1z_nY7BLHgON0MJqMHe_fCL21xfJDwoD2BMA=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11td8y8jrl&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jyhdGOsbmAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBCnJlc3RhdXJhbnSaAURDaTlEUVVsUlFVTnZaRU5vZEhsalJqbHZUMjV3Y2xOSGRHNVZSR2hEWTIxV1VtSlZiRk5sUkd4VFVWWlZNV1ZyUlJBQuABAPoBBAguEEw&phdesc=Ww-OtVSSw5I",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.262995,-97.73012"
        },
        {
          "position": 6,
          "title": "Garage",
          "rating": "4.5",
          "open_state": null,
          "reviews_count": "924",
          "top_review": "The wait staff is extremely attentive and drinks are very high quality.",
          "place_id": "16466347261649349716",
          "description": null,
          "address": "503 Colorado St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267967,
            "longitude": -97.74409
          },
          "type": "Cocktail bar",
          "price": "$20–30",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFGFqIrsgFamBxsWlhAKo6FjdGge6spYGxTqvt_daYlGZU2VUrNCwh2LRaietM9US5WitjgliYzA9TEhQPQp6WwurTbZPLSn_HV6GqmLfx-rJxEDl7o-kHjgszdWZn_1T8GRs2xPQ=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/1pzvrn2mm&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jzlOir-5WAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBDGNvY2t0YWlsX2JhcpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VOc2NFa3pNVXRuRUFF4AEA-gEECHUQRw&phdesc=89vHIRHqPgE",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267967,-97.74409"
        },
        {
          "position": 7,
          "title": "Burger Bar Congress",
          "rating": "4.6",
          "open_state": null,
          "reviews_count": "1.8K",
          "top_review": "The wagyu burger was delicious and the customer service was great!",
          "place_id": "268753694414467468",
          "description": null,
          "address": "110 E 2nd St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.264776,
            "longitude": -97.7438
          },
          "type": "Hamburger",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG6wowLqY0_tkvnc58CeC4kvJcg3EHLgoBr98xGsSmY7z2iun2mjLClJ1XXFEHrGAp-fjAkWQ59mFGpEJPqJC44eoU-qR-P1mbz5sYejnqnIU1-DNqxRJRLiaKtY3timMpK5nU1nA=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11b76k8f1f&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0it6NDonKqAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBFGhhbWJ1cmdlcl9yZXN0YXVyYW50mgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVVJzZDNOaFdYQkJSUkFC4AEA-gEECAAQQg&phdesc=66a-ziYmqmk",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.264776,-97.7438"
        },
        {
          "position": 8,
          "title": "Velvet Taco",
          "rating": "4.7",
          "open_state": null,
          "reviews_count": "3K",
          "top_review": "The cauliflower tacos are delicious, and the red velvet is to die for!",
          "place_id": "11373495270803902317",
          "description": null,
          "address": "522 N Congress Ave Suite 100",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267965,
            "longitude": -97.74308
          },
          "type": "Tacos",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF1ZkCRSo9AMj3mxIFW4UBE6PGXTKT-CNA7qPa22b2L7dLiHnI7zgehwqXtXtqHEXOtqd6A0dFLOV7RM2p4DxBMfZgRKTHVlk4GlNVFnH8ZCxnZJPabHec1Tz_BYvrshPdaH3sK=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11j7y7ckr9&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jpjdfTn7CAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBD3RhY29fcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyMHhNR1Z0U2pKU1YxWktaRlZXU0ZVeU9YQlJhazU1WTFSV1ZtRnRZeEFC4AEA-gEECBIQRg&phdesc=vzGEOF_Pikc",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267965,-97.74308"
        },
        {
          "position": 9,
          "title": "Caroline",
          "rating": "4.8",
          "open_state": "Closed  · Opens 7 AM Fri",
          "reviews_count": "14K",
          "top_review": "I got their Wagyu burger, and it was the best burger that I have ever had.",
          "place_id": "4093074264320094839",
          "description": null,
          "address": "621 N Congress Ave Suite 101",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.268816,
            "longitude": -97.7423
          },
          "type": "American",
          "price": "$20–30",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGKZT5HA26Ctm2xTg15ldV7CRfBbOnUjacmM7xYcJH7Vh0I9cM0eNm3emWLHgptRjwY2a7jA6OCw5xMe3swE2uJJlKKM3JwTDkxIKXp9gtbSpQ5eMfYNIBl5cfN-zZ9H3RsteMF=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11d_9jgz28&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jI8J2Y_ayAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBE2FtZXJpY2FuX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTlVkWFZ1V1RSM1JSQULgAQD6AQQIERBK&phdesc=QoXpuDS8OoM",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.268816,-97.7423"
        },
        {
          "position": 10,
          "title": "Eureka!",
          "rating": "4.4",
          "open_state": "Closes soon  · 12 AM",
          "reviews_count": "3K",
          "top_review": "the appetizers were… *chefs kiss* 🤌🏽 THE TRUFFLE FRIES…",
          "place_id": "6298259428620781736",
          "description": null,
          "address": "200 E 6th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267763,
            "longitude": -97.74129
          },
          "type": "American",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF-gdVCYGXeak7BvbfdlGXQxYBWNAIuWQf9NzDnIRy8nuChZ_z-JFH8sNb60dzNsU9V4H7IlJQkMf7lRzDgNNkAg6F-OPpPPmPuGkOSWJeL-rz1U4oBP0zKt8DB-bClHNM3_js=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11btww44m0&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jgpMi956qAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBE2FtZXJpY2FuX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUXllR1JIZEhwblJSQULgAQD6AQQIRBBC&phdesc=MKlLMBUt0Zw",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267763,-97.74129"
        },
        {
          "position": 11,
          "title": "Roppolo’s Pizzeria",
          "rating": "4.2",
          "open_state": null,
          "reviews_count": "1.1K",
          "top_review": "Comfortable atmosphere  food was nice and warm.",
          "place_id": "14363647147486768618",
          "description": null,
          "address": "316 E 6th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.26741,
            "longitude": -97.7397
          },
          "type": "Pizza",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEuRM1t_HakEY6avy7qOl3GRqWFH95IRYxfDYRdxDTKupkipBlleNdA1FVHeE7_-Hj0RR7UuKyJIADFeOcn5RgcN1GoEJQ0vpl18SFVvij9yCMOF4GoTb0KwDh7WdUqoKEaSs5Seg=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/m/020z7mt&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0j5vLwgWhUQACILcmVzdGF1cmFudHMqBAgDEACSARBwaXp6YV9yZXN0YXVyYW50mgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVVJNTVhCMU9YaFJSUkFC4AEA-gEECCQQLw&phdesc=_EsrR3yf7dw",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.26741,-97.7397"
        },
        {
          "position": 12,
          "title": "Upstairs at Caroline",
          "rating": "4.9",
          "open_state": "Closes soon  · 12 AM",
          "reviews_count": "6.7K",
          "top_review": "Great vibe, very fresh, lots of windows and good lighting, and great food.",
          "place_id": "795394951073857977",
          "description": null,
          "address": "109 E 7th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.268663,
            "longitude": -97.74206
          },
          "type": "American",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEVRsp3_38IXgkICmSCEnwNaSwxZkZZ1KusiGdeSMx1fBHFzSxqJbDbql5Lj5j6od_gxdC2r22YP8VJ5axOEDbsbM4YM_BaSbtu4BdSqaqm2S_HlNsv7a_lXf5EyMspSWnm8FE=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11fxb7wz06&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iG8Pej8a2AgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBE2FtZXJpY2FuX3Jlc3RhdXJhbnSaAURDaTlEUVVsUlFVTnZaRU5vZEhsalJqbHZUMnRvVlU0d1VtaE5NV3gxVFVNeGRFMVliR3hWYlhoRVpFUlJNbGd6WXhBQuABAPoBBAgdEEo&phdesc=w-0q5qLVvLQ",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.268663,-97.74206"
        },
        {
          "position": 13,
          "title": "Comedor",
          "rating": "4.4",
          "open_state": "Closed  · Opens 5 PM Fri",
          "reviews_count": "1K",
          "top_review": "The Tuna Aguachile, Fish Tacos, Bone Marrow Tacos and Ribs were delicious!",
          "place_id": "6958240678106455106",
          "description": null,
          "address": "501 Colorado St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.2676,
            "longitude": -97.74416
          },
          "type": "Restaurant",
          "price": "$50–100",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF0wl6vnwTZtUj5bTeTC-yljDb2-Fx8q3BdGU46OXRUU_z5EJ0FcVSz66qB3G6o7dcOTZ22Xo_9I1mn0WgylKDXTPZMwpB0m-I2_xq2JbwxBoSHuJb_u0TFDSiX_5hNE-icP19AWQ=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11h6rr19fb&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iqy8L7mq-AgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBCnJlc3RhdXJhbnSaASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVUlNhM1ZEVDB4M0VBReABAPoBBQj0BhBK&phdesc=D7PEhzeYgd8",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.2676,-97.74416"
        },
        {
          "position": 14,
          "title": "DittyDog - Downtown",
          "rating": "4.8",
          "open_state": null,
          "reviews_count": "409",
          "top_review": "The food is delicious and the service is incredible.",
          "place_id": "7886117609305430771",
          "description": null,
          "address": "519 E 7th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267345,
            "longitude": -97.73712
          },
          "type": "Restaurant",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGEGXxVBXAw8fLguLNgsd4RmAHmCivTQSlNfbP2_8EbAHlbtnBvvdXcdVuh7kRIXrnp9sNuvO4ZYnyZg-ogJ9kQXPPBGFjuBq1qcC6_nkn-Ks8lwis3WiOTglTSqJnsh8xkKEwF=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11h04p5yng&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iO7cvKgK-AgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBCnJlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUk9aMDgzWDNKUlJSQULgAQD6AQQIABA0&phdesc=UCRs9tE_Y-w",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267345,-97.73712"
        },
        {
          "position": 15,
          "title": "The Onion",
          "rating": "4.2",
          "open_state": null,
          "reviews_count": "424",
          "top_review": "Amazing service and lovely atmosphere, it’s so cozy.",
          "place_id": "12932225639602287481",
          "description": null,
          "address": "408 Brazos St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.266493,
            "longitude": -97.74208
          },
          "type": "Pizza",
          "price": "$1–10",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHFXLzEDvuhyY11Slo-EEINoTL-aasvBSmxhy1oVAHkunQN-c0XzcPWwApZuxbKM9NpUQQYrTm4qPflkOH2M1yZF4d6BE8BIYJLCZjnY9Svq_MWPiDiCT8FvbPnZqLIxzDK-GLC=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/1v44qt8w&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0ibyq3C6ICAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBEHBpenphX3Jlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUlVjbkJJV0RGblJSQULgAQD6AQQIIxA0&phdesc=c0t1rPcY0O4",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.266493,-97.74208"
        },
        {
          "position": 16,
          "title": "Red Ash",
          "rating": "4.7",
          "open_state": "Closed  · Opens 5 PM Fri",
          "reviews_count": "2.4K",
          "top_review": "Great cocktails, service was nice, and the food was fantastic!",
          "place_id": "781942648408772286",
          "description": null,
          "address": "Colorado Tower, 303 Colorado St #200",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.265642,
            "longitude": -97.74485
          },
          "type": "Italian",
          "price": "$50–100",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAELV4PVE1GRObydQehzEEzL4y2_7W7DFjomV4iHbNiO1jX_0NZXJ5pxV4_KvxdNEhFrap8unexAaa9KI_AIsowqEszB9UsxQCyOXVa8TlmrSXtGkF_HPfblSgKAaHpknFpEK0fRnw=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11cs5wlpxh&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iPr-Xd4KuAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBEml0YWxpYW5fcmVzdGF1cmFudJoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VNMmJqaFlSVFpuUlJBQuABAPoBBAgJED4&phdesc=s1JAUKRKu5w",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.265642,-97.74485"
        },
        {
          "position": 17,
          "title": "Friends Bar",
          "rating": "4.6",
          "open_state": null,
          "reviews_count": "1.4K",
          "top_review": "Great brisket tacos, chicharrón style chips and queso, and more.",
          "place_id": "14398074135839074626",
          "description": null,
          "address": "208 E 6th St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267677,
            "longitude": -97.741
          },
          "type": "Live music bar",
          "price": "$20–30",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHVr6KjBj64JV0kLAbhMzDO-yIliazKBXdJUhJ740PnQvJqI3L60Dcu8XXzxM7wC3GvWK-KLGdhRrN2g_OK1YLiNEBlKeaKVr7F-A6hiFTKRxeiSXF4FWRYdbhB4qqe1QTiWiUy=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/m/0k1m7r7&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jnveaQAloVEAAiC3Jlc3RhdXJhbnRzKgQIAxAAkgEObGl2ZV9tdXNpY19iYXKaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUm9NVFZNVjNWQlJSQULgAQD6AQUIhwMQQA&phdesc=ZBa7kcqrUwc",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267677,-97.741"
        },
        {
          "position": 18,
          "title": "Corinne Austin",
          "rating": "4.8",
          "open_state": "Closed  · Opens 7 AM Fri",
          "reviews_count": "5.9K",
          "top_review": "The wagyu burger was cooked perfectly and the desserts were one of a kind!",
          "place_id": "3011152290769757888",
          "description": null,
          "address": "304 E Cesar Chavez St",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.262701,
            "longitude": -97.74158
          },
          "type": "Restaurant",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEOiItBEkLG3CnXiB7jgTJxir-zidTBHOQNUKFkQjikTbAZtjynEJ8ltBi3_cBcbGKV_PmC3kTNdqbTFsmibh7-IL-OojV9UXw9BUR_gJ6JkvI3tRwSnltNMybBsh4WhsL7Ekaxvg=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11n5pb_qpg&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0iutb_VlrSAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBCnJlc3RhdXJhbnSaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTmFlVkJEVFRaM1JSQULgAQD6AQQIfRBK&phdesc=guCTXDznWeA",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.262701,-97.74158"
        },
        {
          "position": 19,
          "title": "Shiner&apos;s Saloon",
          "rating": "4.5",
          "open_state": null,
          "reviews_count": "887",
          "top_review": "Awesome view of the skyline on their terrace and the food is solid!",
          "place_id": "5043695137540684293",
          "description": null,
          "address": "422 N Congress Ave D",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.267084,
            "longitude": -97.7435
          },
          "type": "Bar",
          "price": "$10–20",
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEaKaahQloUYtk1n84kEr_np1dO32C1ANh6FxjB1cFSvJhWboq25jOs-soVTpYJ2ZiJCG3d7Q5urtNS7QN8id39WnVxc_MR8Z6xkrdXVOtKlGREMcvYWy4vjVpgw_-G9qHCdEjE=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11b77g7sh9&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0jpw4_3nKqAgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBA2JhcpoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VRNWVHTllUa2wzRUFF4AEA-gEECAAQQw&phdesc=2C-V1Jr4vgE",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.267084,-97.7435"
        },
        {
          "position": 20,
          "title": "ATX Cocina",
          "rating": "4.6",
          "open_state": "Closed  · Opens 4 PM Fri",
          "reviews_count": "1.9K",
          "top_review": "Great food, delicious drinks, fun outdoor patio, awesome service!",
          "place_id": "11583542460671829300",
          "description": null,
          "address": "110 San Antonio St #170",
          "amenities": null,
          "gps_coordinates": {
            "latitude": 30.26492,
            "longitude": -97.74928
          },
          "type": "Mexican",
          "price": null,
          "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE100CP6fMfXZIy_HHC9RWWQj0aLw6bcQ0gkTPHVBUc-Hs6pDs17AMlHeE4qJx3rHIvzX05lIQYCGPkIbkKpDhn100bBM4jrXhin21oNJ4hZGMCFbJadqeQtKmO7hRK_bJvPQNT=w92-h92-n-k-no",
          "service_options": null,
          "url": "https://www.google.com/viewer/place?sca_esv=ff0cf9ce6af69c53&hl=en&gl=US&udm=1&output=search&mid=/g/11fxb5hwhn&pip=CgtSZXN0YXVyYW50cxAC&lqi=CgtSZXN0YXVyYW50c0j029-i8a2AgAhaFRAAIgtyZXN0YXVyYW50cyoECAMQAJIBEm1leGljYW5fcmVzdGF1cmFudJoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VOb05uUk1aM2xCUlJBQuABAPoBBAgAEEE&phdesc=awGWoZp6QrM",
          "website_url": null,
          "map_url": "https://www.google.com/maps/dir/?api=1&destination=30.26492,-97.74928"
        }
      ]
    }
  }
} as const;
