const jsonResponse = {
  "status": "success",
  "msg": "Task(s) successfully scheduled",
  "results": [
    {
      "user_id": 4281,
      "se": "bing",
      "q": "Electric Vehicles",
      "domain": "bing.com",
      "lang": "en-IN",
      "country_iso": "IN",
      "loc": "Surat,Gujarat,India",
      "lat": "21.17",
      "long": "72.83",
      "device": "desktop",
      "serp_type": "web",
      "verbatim": 0,
      "date_range": null,
      "gfilter": 1,
      "pingback_url": null,
      "postback_url": null,
      "is_scheduled": 1,
      "page": 1,
      "num_result": 10,
      "updated_at": "2026-08-03T09:08:04.000000Z",
      "created_at": "2026-08-03T09:08:04.000000Z",
      "id": 259423989
    },
    {
      "user_id": 4281,
      "se": "google",
      "q": "TeOlympicsa",
      "domain": "google.com",
      "lang": "en",
      "country_iso": "IN",
      "loc": "Surat,Gujarat,India",
      "lat": "21.17",
      "long": "72.83",
      "device": "mobile",
      "serp_type": "web",
      "verbatim": 0,
      "date_range": null,
      "gfilter": 1,
      "pingback_url": null,
      "postback_url": null,
      "is_scheduled": 1,
      "page": 1,
      "num_result": 10,
      "updated_at": "2026-08-03T09:08:04.000000Z",
      "created_at": "2026-08-03T09:08:04.000000Z",
      "id": 259423990
    },
    {
      "user_id": 4281,
      "se": "yahoo",
      "q": "Healthy Recipes",
      "domain": "us.yahoo.com",
      "lang": "lang_en",
      "country_iso": "IN",
      "loc": "Surat,Gujarat,India",
      "lat": "21.17",
      "long": "72.83",
      "device": "desktop",
      "serp_type": "web",
      "verbatim": 0,
      "date_range": null,
      "gfilter": 1,
      "pingback_url": null,
      "postback_url": null,
      "is_scheduled": 1,
      "page": 1,
      "num_result": 10,
      "updated_at": "2026-08-03T09:08:04.000000Z",
      "created_at": "2026-08-03T09:08:04.000000Z",
      "id": 259423991
    }
  ]
} as const;

export const scheduleSerpJsonResponse = jsonResponse as Record<string, unknown>;
